---
title: Project title
author: by Team name
output: github_document
---

## Summary

Write-up of your project and findings go here. 
Think of this as the text of your presentation. 
The length should be roughly 5 minutes when read out loud.
Although pacing varies, a 5-minute speech is roughly 750 words. 
To use the word count addin, select the text you want to count the words of (probably this is the 
Summary section of this document, go to Addins, and select the `Word count` addin).
This addin counts words using two different algorithms, but the results should be similar and as long as you're in the ballpark of 750 words, you're good! 
The addin will ignore code chunks and only count the words in prose.

You can also load your data here and present any analysis results / plots, but I strongly urge you to keep that to a minimum (maybe only the most important graphic, if you have one you can choose). 
And make sure to hide your code with  `echo = FALSE` unless the point you are trying to make is about the code itself.
Your results with proper output and graphics go in your presentation, this space is for a brief summary of your project.

```{r load-data, echo = FALSE}
# load data here, if you like
```

## Presentation

Our presentation can be found [here](presentation/presentation.html).

## Data 

Data source: 
Monson, D. H., Kloecker, K. A. and Esslinger, G. G., 2021, Morphometric and reproductive status data for Sea Otters collected or captured in Alaska: U.S. Geological Survey data release, https://doi.org/10.5066/P9Q5PD3Y.

Referenced Publications(s): 
Tinker, M. T., J. L. Bodkin, L. Bowen, B. E. Ballachey, G. Bentall, A. M. Burdin, H. A. Coletti, G. G. Esslinger, B. B. Hatfield, M. C. Kenner, K. A. Kloecker, B. H. Konar, A. K. Miles, D. H. Monson, M. J. Murray, B. P. Weitzman, and J. A. Estes. 2021. Sea otter population collapse in southwest Alaska: assessing ecological covariates, consequences, and causal factors. Ecological Monographs 91(4):e01472. doi:10.1002/ecm.1472

Laidre, K. L., J. A. Estes, M. T. Tinker, J. L. Bodkin, D. H. Monson, K. Schneider, and M. P. Gillingham. 2006. Patterns of growth and body condition in sea otters from the Aleutian archipelago before and after the recent population decline. Journal of Animal Ecology 75(4):978-989. doi:10.1111/j.1365-2656.2006.01117.x

Monson, D. H. and L. Bowen. 2015. Evaluating the status of individuals and populations: Advantages of multiple approaches and time scales. Pages 121-158 in Larson, S., J. L. Bodkin, and G. R. VanBlaricom (eds) Sea Otter Conservation. Academic Press Boston, MA, USA. doi:10.1016/B978-0-12-801402-8.00006-8

Monson, D. H., J. A. Estes, J. L. Bodkin, and D. B. Siniff. 2000. Life history plasticity and population regulation in sea otters. Oikos 90(3):457-468. doi:10.1034/j.1600-0706.2000.900304.x

## References

Data source: 
Monson, D. H., Kloecker, K. A. and Esslinger, G. G., 2021, Morphometric and reproductive status data for Sea Otters collected or captured in Alaska: U.S. Geological Survey data release, https://doi.org/10.5066/P9Q5PD3Y.

