---
title: "Analysis"
author: "Autumn Pauly"
output: github_document
---

```{r loading-packages}
library(tidyverse)
```

```{r loading-dataset}
base_dir="/Users/pauly/Documents/GitHub/project-ds-2-autumn/project-ds-2-autumn/data/"

seot = read.csv(paste0(base_dir,"seot_morphometricsReproStatus_ak_monson.csv"),h=T)
```

```{r glimpsing data}
seot %>% 
  ggplot(aes(x = YEAR, fill = "firebrick")) +
  geom_histogram(binwidth = 1) + 
  labs(title = "Count of Observations Per Year",
       x = "Year", 
       y = "Count")
```

```{r average-weight-by-year}
ggplot(data = seot, mapping = aes(x = YEAR, y = WEIGHT, color = SEX)) + 
  geom_jitter()

#bacula length
seot %>% 
  filter(BACULA_LGTH = BACULA_LGTH > 0) %>% 
ggplot(data = seot, mapping = aes(x = BACULA_LGTH, fill = SEX)) + 
  geom_histogram() + 
  xlim(5, 20) + 
  facet_wrap(~YEAR)
```


``` {r - tail-length}
#tail length
seot %>% 
ggplot(data = seot, mapping = aes(x = TAIL_LGTH_1)) + 
  geom_histogram() + 
  xlim(10, 40) + 
  facet_wrap(~SEx)
```

